export { zip } from './arrayops'
export { tojs } from './erectObject'
export { flat } from './flat'
export { locate } from './locate'
export { isRxType } from './isRxType'
export { compareKeyPath, pickEntries } from './keyPath'
export { findIndex, isequal, isSubset, isSuperset } from './setops'
