import { hyperscript } from './hyperscript'

export function a         (props, ...children) { return hyperscript('a', ...Array.from         (arguments)) }
export function abbr      (props, ...children) { return hyperscript('abbr', ...Array.from      (arguments)) }
export function address   (props, ...children) { return hyperscript('address', ...Array.from   (arguments)) }
export function area      (props, ...children) { return hyperscript('area', ...Array.from      (arguments)) }
export function article   (props, ...children) { return hyperscript('article', ...Array.from   (arguments)) }
export function aside     (props, ...children) { return hyperscript('aside', ...Array.from     (arguments)) }
export function audio     (props, ...children) { return hyperscript('audio', ...Array.from     (arguments)) }
export function b         (props, ...children) { return hyperscript('b', ...Array.from         (arguments)) }
export function bdi       (props, ...children) { return hyperscript('bdi', ...Array.from       (arguments)) }
export function bdo       (props, ...children) { return hyperscript('bdo', ...Array.from       (arguments)) }
export function blockquote(props, ...children) { return hyperscript('blockquote', ...Array.from(arguments)) }
export function br        (props, ...children) { return hyperscript('br', ...Array.from        (arguments)) }
export function button    (props, ...children) { return hyperscript('button', ...Array.from    (arguments)) }
export function caption   (props, ...children) { return hyperscript('caption', ...Array.from   (arguments)) }
export function cite      (props, ...children) { return hyperscript('cite', ...Array.from      (arguments)) }
export function code      (props, ...children) { return hyperscript('code', ...Array.from      (arguments)) }
export function col       (props, ...children) { return hyperscript('col', ...Array.from       (arguments)) }
export function colgroup  (props, ...children) { return hyperscript('colgroup', ...Array.from  (arguments)) }
export function data      (props, ...children) { return hyperscript('data', ...Array.from      (arguments)) }
export function datalist  (props, ...children) { return hyperscript('datalist', ...Array.from  (arguments)) }
export function dd        (props, ...children) { return hyperscript('dd', ...Array.from        (arguments)) }
export function del       (props, ...children) { return hyperscript('del', ...Array.from       (arguments)) }
export function details   (props, ...children) { return hyperscript('details', ...Array.from   (arguments)) }
export function dfn       (props, ...children) { return hyperscript('dfn', ...Array.from       (arguments)) }
export function dialog    (props, ...children) { return hyperscript('dialog', ...Array.from    (arguments)) }
export function div       (props, ...children) { return hyperscript('div', ...Array.from       (arguments)) }
export function dl        (props, ...children) { return hyperscript('dl', ...Array.from        (arguments)) }
export function dt        (props, ...children) { return hyperscript('dt', ...Array.from        (arguments)) }
export function em        (props, ...children) { return hyperscript('em', ...Array.from        (arguments)) }
export function fieldset  (props, ...children) { return hyperscript('fieldset', ...Array.from  (arguments)) }
export function figcaption(props, ...children) { return hyperscript('figcaption', ...Array.from(arguments)) }
export function figure    (props, ...children) { return hyperscript('figure', ...Array.from    (arguments)) }
export function footer    (props, ...children) { return hyperscript('footer', ...Array.from    (arguments)) }
export function form      (props, ...children) { return hyperscript('form', ...Array.from      (arguments)) }
export function h1        (props, ...children) { return hyperscript('h1', ...Array.from        (arguments)) }
export function h2        (props, ...children) { return hyperscript('h2', ...Array.from        (arguments)) }
export function h3        (props, ...children) { return hyperscript('h3', ...Array.from        (arguments)) }
export function h4        (props, ...children) { return hyperscript('h4', ...Array.from        (arguments)) }
export function h5        (props, ...children) { return hyperscript('h5', ...Array.from        (arguments)) }
export function h6        (props, ...children) { return hyperscript('h6', ...Array.from        (arguments)) }
export function header    (props, ...children) { return hyperscript('header', ...Array.from    (arguments)) }
export function hgroup    (props, ...children) { return hyperscript('hgroup', ...Array.from    (arguments)) }
export function hr        (props, ...children) { return hyperscript('hr', ...Array.from        (arguments)) }
export function i         (props, ...children) { return hyperscript('i', ...Array.from         (arguments)) }
export function img       (props, ...children) { return hyperscript('img', ...Array.from       (arguments)) }
export function input     (props, ...children) { return hyperscript('input', ...Array.from     (arguments)) }
export function ins       (props, ...children) { return hyperscript('ins', ...Array.from       (arguments)) }
export function kbd       (props, ...children) { return hyperscript('kbd', ...Array.from       (arguments)) }
export function label     (props, ...children) { return hyperscript('label', ...Array.from     (arguments)) }
export function legend    (props, ...children) { return hyperscript('legend', ...Array.from    (arguments)) }
export function li        (props, ...children) { return hyperscript('li', ...Array.from        (arguments)) }
export function main      (props, ...children) { return hyperscript('main', ...Array.from      (arguments)) }
export function mark      (props, ...children) { return hyperscript('mark', ...Array.from      (arguments)) }
export function menu      (props, ...children) { return hyperscript('menu', ...Array.from      (arguments)) }
export function menuitem  (props, ...children) { return hyperscript('menuitem', ...Array.from  (arguments)) }
export function meter     (props, ...children) { return hyperscript('meter', ...Array.from     (arguments)) }
export function nav       (props, ...children) { return hyperscript('nav', ...Array.from       (arguments)) }
export function ol        (props, ...children) { return hyperscript('ol', ...Array.from        (arguments)) }
export function optgroup  (props, ...children) { return hyperscript('optgroup', ...Array.from  (arguments)) }
export function option    (props, ...children) { return hyperscript('option', ...Array.from    (arguments)) }
export function output    (props, ...children) { return hyperscript('output', ...Array.from    (arguments)) }
export function p         (props, ...children) { return hyperscript('p', ...Array.from         (arguments)) }
export function pre       (props, ...children) { return hyperscript('pre', ...Array.from       (arguments)) }
export function progress  (props, ...children) { return hyperscript('progress', ...Array.from  (arguments)) }
export function q         (props, ...children) { return hyperscript('q', ...Array.from         (arguments)) }
export function rb        (props, ...children) { return hyperscript('rb', ...Array.from        (arguments)) }
export function rp        (props, ...children) { return hyperscript('rp', ...Array.from        (arguments)) }
export function rt        (props, ...children) { return hyperscript('rt', ...Array.from        (arguments)) }
export function rtc       (props, ...children) { return hyperscript('rtc', ...Array.from       (arguments)) }
export function ruby      (props, ...children) { return hyperscript('ruby', ...Array.from      (arguments)) }
export function s         (props, ...children) { return hyperscript('s', ...Array.from         (arguments)) }
export function samp      (props, ...children) { return hyperscript('samp', ...Array.from      (arguments)) }
export function section   (props, ...children) { return hyperscript('section', ...Array.from   (arguments)) }
export function select    (props, ...children) { return hyperscript('select', ...Array.from    (arguments)) }
export function small     (props, ...children) { return hyperscript('small', ...Array.from     (arguments)) }
export function span      (props, ...children) { return hyperscript('span', ...Array.from      (arguments)) }
export function strong    (props, ...children) { return hyperscript('strong', ...Array.from    (arguments)) }
export function sub       (props, ...children) { return hyperscript('sub', ...Array.from       (arguments)) }
export function summary   (props, ...children) { return hyperscript('summary', ...Array.from   (arguments)) }
export function sup       (props, ...children) { return hyperscript('sup', ...Array.from       (arguments)) }
export function table     (props, ...children) { return hyperscript('table', ...Array.from     (arguments)) }
export function tbody     (props, ...children) { return hyperscript('tbody', ...Array.from     (arguments)) }
export function td        (props, ...children) { return hyperscript('td', ...Array.from        (arguments)) }
export function textarea  (props, ...children) { return hyperscript('textarea', ...Array.from  (arguments)) }
export function tfoot     (props, ...children) { return hyperscript('tfoot', ...Array.from     (arguments)) }
export function th        (props, ...children) { return hyperscript('th', ...Array.from        (arguments)) }
export function thead     (props, ...children) { return hyperscript('thead', ...Array.from     (arguments)) }
export function time      (props, ...children) { return hyperscript('time', ...Array.from      (arguments)) }
export function tr        (props, ...children) { return hyperscript('tr', ...Array.from        (arguments)) }
export function track     (props, ...children) { return hyperscript('track', ...Array.from     (arguments)) }
export function tt        (props, ...children) { return hyperscript('tt', ...Array.from        (arguments)) }
export function u         (props, ...children) { return hyperscript('u', ...Array.from         (arguments)) }
export function ul        (props, ...children) { return hyperscript('ul', ...Array.from        (arguments)) }
export function video     (props, ...children) { return hyperscript('video', ...Array.from     (arguments)) }
export function wbr       (props, ...children) { return hyperscript('wbr', ...Array.from       (arguments)) }